[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["cd thinkmate-next && npm ci"]

[phases.build]
cmds = ["cd thinkmate-next && npm run build"]

[start]
cmd = "cd thinkmate-next && npm start"
