[build]
builder = "nixpacks"
buildCommand = "cd thinkmate-next && npm ci && npm run build"

[deploy]
startCommand = "cd thinkmate-next && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
